"""empty message

Revision ID: 0891a916668b
Revises: 0eb6bf7b6c6d
Create Date: 2023-10-31 00:37:58.687218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0891a916668b'
down_revision = '0eb6bf7b6c6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal', schema=None) as batch_op:
        batch_op.drop_constraint('journal_name_key', type_='unique')
        batch_op.drop_constraint('journal_text_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal', schema=None) as batch_op:
        batch_op.create_unique_constraint('journal_text_key', ['text'])
        batch_op.create_unique_constraint('journal_name_key', ['name'])

    # ### end Alembic commands ###
