"""empty message

Revision ID: 0fd6cec8013a
Revises: 9acfa791a921
Create Date: 2023-11-10 14:41:53.838473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fd6cec8013a'
down_revision = '9acfa791a921'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habit', schema=None) as batch_op:
        batch_op.drop_constraint('habit_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habit', schema=None) as batch_op:
        batch_op.create_unique_constraint('habit_name_key', ['name'])

    # ### end Alembic commands ###
