"""empty message

Revision ID: 643eabf982d8
Revises: 4ff76dbda1ca
Create Date: 2023-10-29 20:44:04.124791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '643eabf982d8'
down_revision = '4ff76dbda1ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('text', sa.String(length=120), nullable=False),
    sa.Column('color', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('text')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('journal')
    # ### end Alembic commands ###
